'''
CREATE TABLE public.candidates (
  id                       text,
  last_name                text,
  first_name               text,
  description              text,
  status                   text,
  status_expired_set       text,
  current_status_interview text,
  datenquelle              text,
  adresse                  text,
  strasse                  text,
  hausnummer               text,
  plz                      text,
  arbeitsort               text,
  wohnort                  text,
  wunscharbeitsort         text,
  umzugszwang              text,
  available                text,
  regionale_verfuegbarkeit text,
  position_now             text,
  next_career_step         text,
  qualification            text,
  department               text,
  short_note               text,
  long_note                text,
  e_mail                   text,
  tel                      text,
  linkedin                 text,
  anlage_wann              text,
  minicrm_id               text,
  how_where_contacted      text,
  export_timestamp         text,
  export_date              text
)

'''